export const personalInfo = {
  name: 'Bal Kishan',
  title: 'Full Stack Engineer',
  tagline: 'Building scalable systems at the intersection of performance & intelligence.',
  email: '11balkishan11@gmail.com',
  phone: '+91-8447660802',
  location: 'New Delhi, India',
  github: 'https://github.com/balkishan69',
  linkedin: 'https://www.linkedin.com/in/bal-kishan-088112289/',
  twitter: 'https://twitter.com/balkishanm69',
  medium: 'https://medium.com/@balkishanmandal',
  leetcode: 'https://leetcode.com/balkishan69',
  codeforces: 'https://codeforces.com/profile/balkishan69',
  codechef: 'https://www.codechef.com/users/balkishan69',
  roles: [
    'Full Stack Engineer',
    'MERN Stack Developer',
    'AI Systems Builder',
    'Backend Engineer',
    'Competitive Programmer',
  ],
};

export const stats = [
  { label: 'DSA Problems', value: '1000+', sub: 'Across platforms' },
  { label: 'LeetCode Rating', value: '1948', sub: 'Knight — Top 3%' },
  { label: 'Projects Shipped', value: '15+', sub: 'Production-grade' },
  { label: 'API Requests/Day', value: '10K+', sub: 'Handled at Bluestock' },
];

export const education = [
  {
    degree: 'B.Tech Computer Science & Engineering',
    institution: 'AKTU University',
    location: 'Greater Noida, India',
    duration: 'Sep 2022 – May 2026',
    grade: 'Completed',
    courses: ['Data Structures & Algorithms', 'Operating Systems', 'DBMS', 'Computer Networks', 'System Design'],
  },
  {
    degree: 'Class XII (CBSE)',
    institution: 'Navyug School, Moti Bagh',
    location: 'New Delhi',
    duration: '2020 – 2021',
    grade: '84%',
    courses: [],
  },
  {
    degree: 'Class X (CBSE)',
    institution: 'Sarvodaya Bal Vidyalaya, Naraina',
    location: 'New Delhi',
    duration: '2018 – 2019',
    grade: '77%',
    courses: [],
  },
];

export const experience = [
  {
    role: 'Software Development Engineer Intern',
    company: 'Bluestock Fintech',
    type: 'Remote',
    duration: 'Feb 2025 – Mar 2025',
    tech: ['Node.js', 'Express.js', 'React.js', 'MongoDB', 'JWT', 'Tailwind CSS'],
    highlights: [
      'Engineered scalable RESTful APIs processing 10,000+ daily requests with 30% response time reduction',
      'Built responsive React frontends reducing page load times by 25%',
      'Optimized MongoDB schemas and query patterns, cutting retrieval latency by 40%',
      'Implemented JWT authentication with RBAC securing access for 5,000+ users',
    ],
    logo: '🏦',
  },
];

export const projects = [
  {
    id: 'codesage',
    title: 'CodeSage AI',
    subtitle: 'LLM-Powered Code Intelligence Platform',
    description: 'Production-grade AI platform that analyzes GitHub repositories simultaneously using RAG pipelines, providing intelligent code explanations, debugging support, and architecture insights — reducing developer onboarding time by 50%.',
    longDescription: 'CodeSage AI combines the power of OpenAI\'s language models with a custom RAG pipeline to deliver sub-second code intelligence. Engineers can query any repository for architecture insights, file-level explanations, and AI-powered debugging — all while the system maintains 45% efficiency gains through intelligent token optimization.',
    tech: ['Python', 'FastAPI', 'OpenAI API', 'RAG Pipeline', 'Vector Search', 'React', 'Node.js', 'MongoDB'],
    metrics: ['50% faster onboarding', '30% token reduction', 'Sub-second responses', '10+ repos simultaneously'],
    github: 'https://github.com/balkishan69/CodeSage-AI-LLM-Powered-Code_Repository-Intelligence-Platform',
    live: 'https://code-sage-ai-eight.vercel.app/',
    featured: true,
    category: 'AI/ML',
    image: '/projects_images/codesage.png',
    color: '#00d4ff',
  },
  {
    id: 'whiteboard',
    title: 'CollabBoard',
    subtitle: 'Real-Time Collaborative Whiteboard',
    description: 'Multi-user real-time whiteboard with WebRTC and Socket.IO achieving sub-100ms sync latency. Supports concurrent sessions with JWT-secured authentication and full CI/CD deployment.',
    longDescription: 'Built with a custom WebSocket architecture, CollabBoard handles concurrent drawing sessions with optimistic UI updates and conflict resolution. The backend handles 30% better query response under concurrent load through optimized MongoDB indexing.',
    tech: ['React.js', 'Node.js', 'Socket.IO', 'WebRTC', 'MongoDB', 'JWT', 'Vercel'],
    metrics: ['<100ms sync latency', '30% query improvement', 'Zero-downtime CI/CD'],
    github: 'https://github.com/balkishan69/whiteboard_project',
    live: 'https://whiteboard-tutorial-eight.vercel.app/',
    featured: true,
    category: 'Full Stack',
    image: '/projects_images/collabBoard.png',
    color: '#00ff88',
  },
  {
    id: 'rubiks',
    title: "Rubik's Cube Solver",
    subtitle: "Korf's IDA* Algorithm Implementation",
    description: 'Advanced C++ implementation of Korf\'s IDA* algorithm with pattern databases. Solves any scramble optimally — 8-move solutions in under 3 seconds, 13-move in under 10 seconds.',
    longDescription: 'A deep-dive into algorithm optimization, this solver implements bidirectional BFS, IDDFS, and IDA* with precomputed pattern databases. The 3x speed improvement comes from optimized heuristic lookups and bitwise cube state representation.',
    tech: ['C++', 'IDA* Algorithm', 'Pattern Databases', 'BFS/DFS', 'CMake', 'Bitwise Ops'],
    metrics: ['3s for 8-move solves', '10s for 13-move solves', '3x speed improvement'],
    github: 'https://github.com/balkishan69/rubik-s-cube-solver',
    live: null,
    featured: true,
    category: 'Algorithms',
    image: '/projects_images/rubikCube.png',
    color: '#ffd700',
  },
  {
    id: 'vaultwise',
    title: 'VaultWise',
    subtitle: 'Personal Finance Tracker',
    description: 'Beautiful finance tracking app with category-wise budgets, interactive Chart.js visualizations, gamified achievements, and smooth Framer Motion animations. Fully responsive with dark/light mode.',
    longDescription: 'VaultWise demonstrates strong product thinking — a gamified achievement system encourages positive financial behaviors while interactive charts deliver clear spending insights. Built with TypeScript for type safety and Framer Motion for polish.',
    tech: ['React 18', 'TypeScript', 'Chart.js', 'Framer Motion', 'Tailwind CSS', 'Vite'],
    metrics: ['Gamified achievements', 'Interactive charts', 'Full responsive'],
    github: 'https://github.com/balkishan69/finance-tracker-app',
    live: 'https://vaultwise.netlify.app/',
    featured: false,
    category: 'Frontend',
    image: '/projects_images/VaultWise.png',
    color: '#00d4ff',
  },
  {
    id: 'pdfbot',
    title: 'PDF Bot',
    subtitle: 'AI Document Q&A System',
    description: 'AI-powered document analysis using Google Gemini 2.0, ChromaDB vector storage, and real-time WebSocket chat. Upload any PDF and have intelligent conversations with your documents.',
    longDescription: 'PDF Bot uses LangChain with Chroma vector DB for semantic search across documents. The FastAPI backend streams responses via WebSockets for a real-time chat experience, with source attribution linking each answer back to specific document sections.',
    tech: ['FastAPI', 'Google Gemini', 'ChromaDB', 'LangChain', 'React 19', 'WebSockets'],
    metrics: ['Real-time streaming', 'Source attribution', 'Semantic search'],
    github: 'https://github.com/balkishan69/pdf-bot-project',
    live: 'https://pdfhelper-bot.vercel.app/',
    featured: false,
    category: 'AI/ML',
    image: '/projects_images/pdfBot.png',
    color: '#00ff88',
  },
  {
    id: 'taskflow',
    title: 'TaskFlow API',
    subtitle: 'Enterprise Task Management Platform',
    description: 'Production-grade REST API platform with JWT auth, RBAC, Swagger docs, rate limiting, and service-layer architecture. Built during Primetrade.ai internship assignment with scalability roadmap.',
    longDescription: 'TaskFlow demonstrates enterprise backend patterns: service layer separation, centralized error handling, bcrypt password hashing, and comprehensive API documentation. The architecture scales horizontally with Redis caching and microservices.',
    tech: ['Node.js', 'Express.js', 'MongoDB', 'JWT', 'Swagger', 'React', 'Tailwind'],
    metrics: ['Swagger API docs', 'Rate limiting', 'RBAC system'],
    github: 'https://github.com/balkishan69/Backend-Development-internship-Primetrade.ai-',
    live: null,
    featured: false,
    category: 'Backend',
    image: '/projects_images/TaskFlow.png',
    color: '#ff6b35',
  },
  {
    id: 'braintumor',
    title: 'Brain Tumor Detection',
    subtitle: 'Deep Learning MRI Analysis',
    description: 'CNN-based classification system for MRI brain scans, detecting Glioma, Meningioma, Pituitary tumors, and healthy tissue — with a web interface for clinical use.',
    longDescription: 'Applying deep learning to healthcare, this system classifies brain MRI images into four categories with high accuracy. Built using convolutional neural networks with a web deployment interface for real-world clinical integration.',
    tech: ['Python', 'Deep Learning', 'CNNs', 'Computer Vision', 'Jupyter', 'Flask'],
    metrics: ['4 tumor types', 'Clinical web UI', 'MRI analysis'],
    github: 'https://github.com/balkishan69/Brain-Tumor-Detection-Using-Deep-Learning-MRI-Images-Detection-Using-Computer-Vision',
    live: null,
    featured: false,
    category: 'AI/ML',
    image: '/projects_images/BrainTumor.png',
    color: '#ff6b35',
  },
];

export const skills = {
  languages: [
    { name: 'JavaScript', level: 95 },
    { name: 'TypeScript', level: 90 },
    { name: 'Python', level: 85 },
    { name: 'C++', level: 88 },
    { name: 'Java', level: 75 },
    { name: 'SQL', level: 82 },
  ],
  frontend: ['React.js', 'Next.js', 'Vue.js', 'Tailwind CSS', 'Framer Motion', 'Redux', 'WebRTC', 'Socket.IO', 'Vite'],
  backend: ['Node.js', 'Express.js', 'FastAPI', 'Flask', 'REST APIs', 'WebSockets', 'JWT/OAuth', 'RBAC'],
  databases: ['MongoDB', 'MySQL', 'PostgreSQL', 'Redis', 'Supabase', 'ChromaDB', 'Mongoose'],
  aiml: ['OpenAI API', 'Google Gemini', 'RAG Pipelines', 'LangChain', 'Vector Search', 'NumPy', 'Pandas'],
  devops: ['Docker', 'Kubernetes', 'Azure', 'Vercel', 'Netlify', 'Render', 'CI/CD', 'Git', 'GitHub'],
  tools: ['Turborepo', 'Swagger', 'Postman', 'CMake', 'Firebase', 'Webpack', 'ESLint'],
};

export const achievements = [
  {
    platform: 'LeetCode',
    badge: 'Knight',
    rating: '1948',
    detail: 'Max Rating — Top 3% globally',
    solved: '300+',
    color: '#f59e0b',
    icon: '⚔️',
    link: 'https://leetcode.com/u/11balkishan11/',
  },
  {
    platform: 'Codeforces',
    badge: 'Specialist',
    rating: '1517',
    detail: 'Max Rating',
    solved: '300+',
    color: '#60a5fa',
    icon: '🔵',
    link: 'https://codeforces.com/profile/11balkishan11',
  },
  {
    platform: 'CodeChef',
    badge: '3 Stars',
    rating: '1795',
    detail: 'Max Rating',
    solved: '200+',
    color: '#a78bfa',
    icon: '⭐',
    link: 'https://www.codechef.com/users/balkishan11',
  },
  {
    platform: 'Meta HackerCup 2024',
    badge: 'Global Rank 6,676',
    rating: 'Top 28%',
    detail: 'Out of 24,000+ participants worldwide',
    solved: '',
    color: '#00d4ff',
    icon: '🏆',
    link: 'https://drive.google.com/file/d/1JkWh1WcyAE-9ChgUPtX_n2R6bxzPw_jD/view',
  },
];

export const certifications = [
  {
    name: 'Full Stack Web Development',
    subtitle: 'MERN, DevOps & System Design',
    issuer: '100xDevs by Harkirat Singh',
    color: '#00d4ff',
    icon: '🚀',
    link: 'https://drive.google.com/file/d/16pahHGxYhyKTOeWS5BNy-5JTK8D3GeSU/view',
  },
  {
    name: 'Machine Learning with Python',
    subtitle: 'ML fundamentals and algorithms',
    issuer: 'IBM',
    color: '#00ff88',
    icon: '🤖',
    link: 'https://courses.cognitiveclass.ai/certificates/adb2da01a49f4398b0f40d8324b8500a',
  },
  {
    name: 'Accelerating Deep Learning with GPUs',
    subtitle: 'GPU computing for neural networks',
    issuer: 'IBM',
    color: '#ff6b35',
    icon: '⚡',
    link: 'https://courses.cognitiveclass.ai/certificates/1a4875e9768249c88e2fc098074ee3c8',
  },
];

export const philosophyQuotes = [
  {
    quote: "I build systems that don't just work — they scale, they perform, and they last.",
    context: 'On Engineering Philosophy',
  },
  {
    quote: "Every bug is a lesson, every optimization is a story, and every shipped product is proof of execution.",
    context: 'On Shipping',
  },
  {
    quote: "Competitive programming sharpened my thinking. Real-world systems sharpened my judgment.",
    context: 'On Growth',
  },
];
